### ISSUE TITLE
Console sample invalid cast exception

### ISSUE THREAD

**Issue by crazy4pi314** [tonybaloney/CSnakes#199]
On a fresh local clone on [main here] (https://github.com/tonybaloney/CSnakes/commit/949b73839fe938a678859dc999e7a3cb92c1e3ce), I use VS to build and run in debug mode the Quick Console Test solution and get this error:

```bash
System.InvalidCastException
  HResult=0x80004002
  Message=Cannot convert [a, 1] to PyObject
  Source=CSnakes.Runtime
  StackTrace:
   at CSnakes.Runtime.Python.PyObject.From[T](T value)
   at CSnakes.Runtime.PyObjectTypeConverter.ConvertFromList(IEnumerable e)
   at CSnakes.Runtime.Python.PyObject.From[T](T value)
   at CSnakes.Runtime.TypeDemosExtensions.TypeDemosInternal.TakeDict(IReadOnlyDictionary`2 d) in C:\Users\sarahkaiser\git\CSnakes\samples\simple\ExamplePythonDependency\obj\Debug\net8.0\generated\CSnakes\CSnakes.PythonStaticGenerator\TypeDemos.py.cs:line 72
   at Program.<<Main>$>g__RunDictionaryDemo|0_2(IPythonEnvironment env) in C:\Users\sarahkaiser\git\CSnakes\samples\simple\QuickConsoleTest\Program.cs:line 51
   at Program.<Main>$(String[] args) in C:\Users\sarahkaiser\git\CSnakes\samples\simple\QuickConsoleTest\Program.cs:line 30
```

Console output:

```bash
info: CSnakes.Runtime.IPythonEnvironment[0]
      Setting up Python environment from C:\Users\sarahkaiser\.nuget\packages\python\3.12.4\tools using home of C:\Users\sarahkaiser\git\CSnakes\samples\simple\QuickConsoleTest\bin\Debug\net8.0\..\..\..\..\ExamplePythonDependency
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      File C:\Users\sarahkaiser\git\CSnakes\samples\simple\QuickConsoleTest\bin\Debug\net8.0\..\..\..\..\ExamplePythonDependency\requirements.txt was found.
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Using virtual environment at C:\Users\sarahkaiser\git\CSnakes\samples\simple\QuickConsoleTest\bin\Debug\net8.0\..\..\..\..\ExamplePythonDependency\.venv to install packages with pip.
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: numpy in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from -r requirements.txt (line 1)) (2.1.1)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: scikit-learn in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from -r requirements.txt (line 2)) (1.5.2)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: wheel in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from -r requirements.txt (line 3)) (0.44.0)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: transformers in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from -r requirements.txt (line 4)) (4.44.2)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: scipy>=1.6.0 in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from scikit-learn->-r requirements.txt (line 2)) (1.14.1)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: joblib>=1.2.0 in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from scikit-learn->-r requirements.txt (line 2)) (1.4.2)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from scikit-learn->-r requirements.txt (line 2)) (3.5.0)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: filelock in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from transformers->-r requirements.txt (line 4)) (3.16.0)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from transformers->-r requirements.txt (line 4)) (0.24.7)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: packaging>=20.0 in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from transformers->-r requirements.txt (line 4)) (24.1)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: pyyaml>=5.1 in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from transformers->-r requirements.txt (line 4)) (6.0.2)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: regex!=2019.12.17 in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from transformers->-r requirements.txt (line 4)) (2024.9.11)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: requests in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from transformers->-r requirements.txt (line 4)) (2.32.3)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: safetensors>=0.4.1 in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from transformers->-r requirements.txt (line 4)) (0.4.5)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: tokenizers<0.20,>=0.19 in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from transformers->-r requirements.txt (line 4)) (0.19.1)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: tqdm>=4.27 in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from transformers->-r requirements.txt (line 4)) (4.66.5)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: fsspec>=2023.5.0 in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from huggingface-hub<1.0,>=0.23.2->transformers->-r requirements.txt (line 4)) (2024.9.0)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from huggingface-hub<1.0,>=0.23.2->transformers->-r requirements.txt (line 4)) (4.12.2)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: colorama in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from tqdm>=4.27->transformers->-r requirements.txt (line 4)) (0.4.6)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from requests->transformers->-r requirements.txt (line 4)) (3.3.2)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: idna<4,>=2.5 in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from requests->transformers->-r requirements.txt (line 4)) (3.10)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from requests->transformers->-r requirements.txt (line 4)) (2.2.3)
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
      Requirement already satisfied: certifi>=2017.4.17 in c:\users\sarahkaiser\git\csnakes\samples\simple\examplepythondependency\.venv\lib\site-packages (from requests->transformers->-r requirements.txt (line 4)) (2024.8.30)
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaa,bbb,ccc
a : 1
b : 2
c : 3
Unhandled exception. System.InvalidCastException: Cannot convert [a, 1] to PyObject
   at CSnakes.Runtime.Python.PyObject.From[T](T value) in /_/src/CSnakes.Runtime/Python/PyObject.cs:line 509
   at CSnakes.Runtime.PyObjectTypeConverter.ConvertFromList(IEnumerable e) in /_/src/CSnakes.Runtime/PyObjectTypeConverter.List.cs:line 40
   at CSnakes.Runtime.Python.PyObject.From[T](T value) in /_/src/CSnakes.Runtime/Python/PyObject.cs:line 507
   at CSnakes.Runtime.TypeDemosExtensions.TypeDemosInternal.TakeDict(IReadOnlyDictionary`2 d) in C:\Users\sarahkaiser\git\CSnakes\samples\simple\ExamplePythonDependency\obj\Debug\net8.0\generated\CSnakes\CSnakes.PythonStaticGenerator\TypeDemos.py.cs:line 72
   at Program.<<Main>$>g__RunDictionaryDemo|0_2(IPythonEnvironment env) in C:\Users\sarahkaiser\git\CSnakes\samples\simple\QuickConsoleTest\Program.cs:line 51
   at Program.<Main>$(String[] args) in C:\Users\sarahkaiser\git\CSnakes\samples\simple\QuickConsoleTest\Program.cs:line 30
```
It should be using the Python env that the C# toolchain installs, not local to my machine, but digging in now.

**Comment by crazy4pi314** [comment]
Ok found the cause, it's the round trip converting the dictionary in `type_demos.py` to C# and back. It should be `dict[str, int]` but somewhere it's getting stuck...

**Comment by tonybaloney** [comment]
> Ok found the cause, it's the round trip converting the dictionary in `type_demos.py` to C# and back. It should be `dict[str, int]` but somewhere it's getting stuck... I am now using the local built version of csnakes nuget pkg just to make sure that it's not a mismatch version error. The dict tests on the library tests pass so I am trying to figure out if I can expand them to repro the sample error.

Interesting. I rewrote the dictionary implementation to be lazy last week so it's likely a bug.

**Comment by atifaziz** [comment]
I think the problem here is that [`PyDictionary`](https://github.com/tonybaloney/CSnakes/blob/834002b602a6bc995d1b61f2cc5bdd69194ebe71/src/CSnakes.Runtime/Python/PyDictionary.cs) implements `IReadOnlyDictionary<,>`, but _not_ `IDictionary`, which is what [`PyObject.From<>`](https://github.com/tonybaloney/CSnakes/blob/834002b602a6bc995d1b61f2cc5bdd69194ebe71/src/CSnakes.Runtime/Python/PyObject.cs#L488-L512) is looking for:

https://github.com/tonybaloney/CSnakes/blob/834002b602a6bc995d1b61f2cc5bdd69194ebe71/src/CSnakes.Runtime/Python/PyObject.cs#L504

However, since `IReadOnlyDictionary<,>` _does_ inherit from `IEnumerable`, it's hitting the following line instead:

https://github.com/tonybaloney/CSnakes/blob/834002b602a6bc995d1b61f2cc5bdd69194ebe71/src/CSnakes.Runtime/Python/PyObject.cs#L507

and treating the dictionary like a sequence of `KeyValuePair<,>` items. Finally, as there isn't a conversion for `KeyValuePair<,>`, it ultimately ends up failing here:

https://github.com/tonybaloney/CSnakes/blob/834002b602a6bc995d1b61f2cc5bdd69194ebe71/src/CSnakes.Runtime/Python/PyObject.cs#L509

with the error `Cannot convert [a, 1] to PyObject` because that's the first pair in the dictionary obtained from:

https://github.com/tonybaloney/CSnakes/blob/834002b602a6bc995d1b61f2cc5bdd69194ebe71/samples/simple/ExamplePythonDependency/type_demos.py#L2

**Comment by tonybaloney** [comment]
Ah now I understand. In the tests, we only ever do a conversion from Dictionary -> Python , from Python. -> PyDictionary. I never tested PyDictionary -> Python but obviously if the demo project does that, it needs to be fixed.

Sounds like the issue is the conversion of the `KeyValuePair` type in particular.

**Comment by tonybaloney** [comment]
Or, if we updated `From<>` to accept the PyDictionary type. That depends on whether `IDictionary` requires methods for writing values (which we don't want)

**Comment by tonybaloney** [comment]
Looks like ReadOnlyDictionary throws NotSupportedException for any of the write methods. WE can adopt the same pattern

https://learn.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.readonlydictionary-2?view=net-8.0

**Comment by tonybaloney** [comment]
On second thoughts, since we're converting back to `PyObject` and `PyDictionary` has the original Python object reference, we should clone that reference and skip the marshalling altogether.
