### ISSUE TITLE
ModuleNotFoundError: No module named distutils

### ISSUE THREAD

**Issue by tjgokken** [tonybaloney/CSnakes#292]
When running a script which is using the following libraries

```
import os
import sys
import json
import numpy as np
import pandas as pd
import logging
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from tensorflow.keras import layers
```

I get the following error: No module named distutils. The script runs fine from the command line or using Process Interop. Here is the Stack Trace:

```
  File "MyPythonScript.py", line 9, in <module>
    from tensorflow import keras

  File "C:\MyEnv\Lib\site-packages\tensorflow\__init__.py", line 30, in <module>
    import distutils as _distutils
```

and CSnakes Stack Trace:

```
  at CSnakes.Runtime.Python.PyObject..ctor(IntPtr pyObject, Boolean ownsHandle)
   at CSnakes.Runtime.Python.PyObject.Create(IntPtr ptr)
   at CSnakes.Runtime.CPython.CPythonAPI.Import(String name)
   at CSnakes.Runtime.Python.Import.ImportModule(String module)
   at CSnakes.Runtime.HousePriceNeuralNetworkExtensions.HousePriceNeuralNetworkInternal..ctor(ILogger`1 logger) in C:\...\obj\Debug\net8.0\CSnakes.SourceGeneration\CSnakes.PythonStaticGenerator\HousePriceNeuralNetwork.py.cs:line 49
   at CSnakes.Runtime.HousePriceNeuralNetworkExtensions.HousePriceNeuralNetwork(IPythonEnvironment env) 

```

**Comment by minesworld** [comment]
strange. Is is possible that this relates to https://github.com/tonybaloney/CSnakes/issues/302 ??

**Comment by jozefhornik** [comment]
I encountered the same issue, and downgrading python from 3.12 to version 3.11 resolved it for me.
